# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rationalize}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh McArthur"]
  s.date = %q{2011-04-08}
  s.email = %q{josh@3months.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/rationalize/translations_controller.rb",
    "app/helpers/application_helper.rb",
    "app/helpers/rationalize/translations_helper.rb",
    "app/views/layouts/rationalize.html.erb",
    "app/views/rationalize/translations/index.html.haml",
    "config/initializers/rationalize_i18n.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/engine.rb",
    "lib/rails/generators/cheese/cheese_generator.rb",
    "lib/rails/generators/cheese/templates/initializer.rb",
    "lib/rails/generators/cheese/templates/migration.rb",
    "lib/rails/generators/cheese/templates/schema.rb",
    "lib/rails/railties/tasks.rake",
    "lib/rationalize.rb",
    "public/stylesheets/rationalize.css"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.0}
  s.summary = %q{A plug-and-play Redis-backed web frontend for I18N translations.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

